<script src="<?=base_url()?>resource/js/jquery-2.1.4.min.js"></script>
<script src="<?=base_url()?>resource/js/jquery.magnific-popup.js"></script>
<script src="<?=base_url()?>resource/js/minicart.js"></script>
<script src="<?=base_url()?>resource/js/jquery-ui.js"></script>
<script src="<?=base_url()?>resource/js/jquery.flexisel.js"></script>
<script src="<?=base_url()?>resource/js/SmoothScroll.min.js"></script>
<script src="<?=base_url()?>resource/js/move-top.js"></script>
<script src="<?=base_url()?>resource/js/easing.js"></script>
<script src="<?=base_url()?>resource/js/bootstrap.js"></script>